services:
  tests:
    build:
      context: .
      target: dev
    environment:
      DB_DSN: postgresql+asyncpg://test:test@tests_db/test
      REDIS_DSN: redis://tests_redis
      S3_ENDPOINT: http://localstack:4566
      S3_REGION_NAME: us-east-1
      S3_ACCESS_KEY_ID: test
      S3_SECRET_ACCESS_KEY_ID: test
      S3_PRIVATE_BUCKET_NAME: test-bucket
      S3_PUBLIC_BUCKET_NAME: test-bucket
      SES_ENDPOINT: http://localstack:4566
      SES_REGION_NAME: us-east-1
      SES_ACCESS_KEY: test
      SES_SECRET_KEY: test
      UNOVAY_EMAIL_FROM: sender@example.com
    volumes:
      - .:/src
    command: >
      bash -c "poetry run alembic upgrade head &&
               poetry run pytest --no-header --no-cov -vv tests"
    networks:
      - tests
    depends_on:
      tests_db:
        condition: service_healthy

  tests_db:
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    command: "postgres -c max_connections=20 -c shared_buffers=200MB"
    networks:
      - tests
    healthcheck:
      test: "pg_isready -U test -d test"
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
      - 5432:5432

  tests_redis:
    image: redis:latest
    command: ["redis-server", "--save", "''", "--dbfilename", "''", "--appendonly", "no", "--appendfsync", "no"]
    networks:
      - tests
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  tests_localstack:
    hostname: localstack
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    networks:
      - tests
    environment:
      SERVICES: s3,ses
      HOSTNAME: localstack
      LOCALSTACK_HOST: localstack
    volumes:
      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh

networks:
  tests:
