"""create_tables.

Revision ID: 16dd19e2a44a
Revises:
Create Date: 2025-08-18 01:08:58.546708

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '16dd19e2a44a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activity',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('parent_id', sa.Uuid(), nullable=True),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['parent_id'], ['activity.id'], name=op.f('activity_parent_id_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('activity_pkey')),
    )
    op.create_table(
        'building',
        sa.Column('address', sa.Text(), nullable=False),
        sa.Column('latitude', sa.Numeric(), nullable=False),
        sa.Column('longitude', sa.Numeric(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('building_pkey')),
    )
    op.create_table(
        'organization',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('building_id', sa.UUID(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['building_id'], ['building.id'], name=op.f('organization_building_id_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('organization_pkey')),
    )
    op.create_table(
        'organization_activity',
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('activity_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
            name=op.f('organization_activity_organization_id_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['activity_id'], ['activity.id'], name=op.f('organization_activity_activity_id_fkey')
        ),
        sa.PrimaryKeyConstraint(
            'organization_id', 'activity_id', name=op.f('organization_activity_pkey')
        ),
    )
    op.create_table(
        'phone',
        sa.Column('number', sa.String(length=20), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['organization_id'], ['organization.id'], name=op.f('phone_organization_id_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('phone_pkey')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone')
    op.drop_table('organization_activity')
    op.drop_table('organization')
    op.drop_table('building')
    op.drop_table('activity')
    # ### end Alembic commands ###
