name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test:
    uses: AldanDev/workflows/.github/workflows/test.yaml@main
    with:
      python-version: '3.13'
  
  changelog:
    needs: test
    permissions: write-all
    uses: AldanDev/workflows/.github/workflows/changelog.yaml@main
    with:
      python-version: '3.13'

  automerge:
    runs-on: ubuntu-latest
    needs: test
    permissions: write-all
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
